on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libsdl2-dev

    - name: Build
      run: make
      
    - name: Set execute permissions
      run: chmod +x my_program
      
    - name: Run tests
      run: make test
